validate-maintainers: false

registry:
  default:
    globalassetid: id
  vite:
    manual: 
      url: https://github.com/catenax-ng/product-item-relationship-service-frontend/blob/main/docs/userManual.md
  url:
    local: http://localhost:8080
keycloak:
  url: http://localhost:4011/connect/token
  grant:
    type: catena-scope
  scope: client_credentials
