validate-maintainers: false

registry:
  default:
    global:
      asset:
        id: id
  vite:
    manual: 
      url: https://github.com/catenax-ng/product-item-relationship-service-frontend/blob/main/docs/userManual.md
  url:
    local: http://localhost:8080
keycloak:
  url: http://localhost:4011/connect/token
  grand:
    type: catena-scope
  scope: client_credentials
  client:
    id: catena-client-id
    secret: catena-client-secret
