---
replicaCount: 1

image:
  repository: ghcr.io/catenax-ng/product-item-relationship-service-frontend
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: ""

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

securityContext:
  # fsGroup: 999
  # runAsUser: 999
  # allowPrivilegeEscalation: false
  # runAsNonRoot: true
  # seccompProfile:
  #   type: RuntimeDefault
  # capabilities:
  #   drop: ["ALL"]

ingress:
  enabled: false
  hosts: []
  tls: []

registry:
  default:
    globalassetid:
    bpn:
  vite:
    manual:
      url:
  url:
    local:
keycloak:
  url:
  grant:
    type:
  scope:

